# Generated by Django 4.0.3 on 2022-04-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, db_column='telefono', max_length=10, null=True, verbose_name='Telefono')),
                ('etiqueta', models.CharField(blank=True, choices=[('movil', 'Movil'), ('home', 'Casa'), ('other', 'Otro')], db_column='etiqueta', max_length=6, null=True, verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Numero Telefonico',
                'db_table': 'numero_telefonico',
            },
        ),
        migrations.CreateModel(
            name='phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, db_column='apellido', max_length=80, null=True, verbose_name='Apellidos')),
                ('nickname', models.CharField(blank=True, db_column='apodo', max_length=20, null=True, verbose_name='Apodo')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=200, null=True, unique=True, verbose_name='Correo electrónico')),
                ('relationship', models.CharField(blank=True, choices=[('assistant', 'Asistente'), ('brosis', 'Hermana/Hermano'), ('motfat', 'Madre/Padre'), ('aunc', 'Tia/Tio'), ('grant', 'Abuela/Abuelo'), ('wihus', 'Esposa/Esposo')], db_column='relacion', max_length=16, null=True, verbose_name='Persona relacionada')),
                ('phone', models.ForeignKey(db_column='telefono', on_delete=django.db.models.deletion.CASCADE, to='agenda.phonenumber', verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Agenda',
                'db_table': 'agenda',
            },
        ),
    ]
