# Generated by Django 4.0.3 on 2022-04-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='relationship',
            field=models.CharField(blank=True, choices=[('assistant', 'Asistente'), ('brother_sister', 'Hermana/Hermano'), ('mother_father', 'Madre/Padre'), ('aunt_uncle', 'Tia/Tio'), ('grant', 'Abuela/Abuelo'), ('wife_husband', 'Esposa/Esposo')], db_column='relacion', max_length=16, null=True, verbose_name='Persona relacionada'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.IntegerField(blank=True, db_column='telefono', null=True, verbose_name='Telefono'),
        ),
    ]
